<?php

// Important: this file must always align with the rankingConstants.ts file in the frontend.

namespace App\Constants;

class RankColumnDefinitions
{
    const RANK_COLS = [
        'wellRank' => 'MCW Rank',
        'wellId' => 'Well ID',
        'operatorName' => 'Operator Name',
        'wellName' => 'Well Name',
        'wellType' => 'Well Type',
        'wellAgeScore' => 'Well Age Score',
        'ownerWellCountScore' => 'Owner Well Count Score',
        'lifelongGasProductionScore' => 'Lifetime Production Volume - Gas Score',
        'lifelongOilProductionScore' => 'Lifetime Production Volume - Oil Score',
        'annGasProductionScore' => 'Annual Production Volume - Gas Score',
        'annOilProductionScore' => 'Annual Production Volume - Oil Score',
        'fiveYearGasProductionScore' => '5 Year Production Volume - Gas Score',
        'fiveYearOilProductionScore' => '5 Year Production Volume - Oil Score',
        'schoolsScore' => 'Sensitive Receptors - Schools Score',
        'hospitalsScore' => 'Sensitive Receptors - Hospitals Score',
        'agricultureAreaNearbyScore' => 'Sensitive Receptors - Agriculture Area Nearby Score',
        'buildingsNearScore' => 'Sensitive Receptors - Buildings (Near) Score',
        'buildingsFarScore' => 'Sensitive Receptors - Buildings (Far) Score',
        'endangeredSpeciesOnSiteScore' => 'Ecological Receptors - Endangered Species on Site Score',
        'waterSourceNearbyScore' => 'Ecological Receptors - Water Source Nearby Score', 'knownSoilOrWaterImpactScore' => 'Ecological Receptors - Known Soil or Water Impact Score',
        'fedWetlandsNearScore' => 'Ecological Receptors - Fed Wetlands (Near) Score',
        'fedWetlandsFarScore' => 'Ecological Receptors - Fed Wetlands (Far) Score',
        'stateWetlandsNearScore' => 'Ecological Receptors - State Wetlands (Near) Score',
        'stateWetlandsFarScore' => 'Ecological Receptors - State Wetlands (Far) Score',
        'historicalPreservationSiteScore' => 'Site Considerations - Historical Preservation Site Score',
        'homeUseGasWellScore' => 'Site Considerations - Home Use Gas Well Score',
        'postPluggingLandUseScore' => 'Site Considerations - Post Plugging Land Use Score',
        'surfaceEquipmentOnSiteScore' => 'Site Considerations - Surface Equipment on Site Score',
        'likelyToBeOrphanedScore' => 'Likely to be Orphaned Score',
        'inTribalLandScore' => 'In Tribal Land Score',
        'costOfPluggingScore' => 'Cost of Plugging Score',
        'highPressureObservedScore' => 'High Pressure Observed Score',
        'idleStatusDurationScore' => 'Idle Status Duration Score',
        'numberOfMcwsNearbyScore' => 'Number Of MCWs Nearby Score',
        'mechanicalIntegrityTestScore' => 'Mechanical Integrity Test Score',
        'otherwiseIncentivizedWellScore' => 'Otherwise Incentivized Well Score',
        'wellIntegrityScore' => 'Well Integrity Score',
        'placeholderOneScore' => 'Placeholder 1 Score',
        'placeholderTwoScore' => 'Placeholder 2 Score',
        'placeholderThreeScore' => 'Placeholder 3 Score',
        'placeholderFourScore' => 'Placeholder 4 Score',
        'placeholderFiveScore' => 'Placeholder 5 Score',
        'placeholderSixScore' => 'Placeholder 6 Score',
        'placeholderSevenScore' => 'Placeholder 7 Score',
        'placeholderEightScore' => 'Placeholder 8 Score',
        'placeholderNineScore' => 'Placeholder 9 Score',
        'placeholderTenScore' => 'Placeholder 10 Score',
        'placeholderElevenScore' => 'Placeholder 11 Score',
        'placeholderTwelveScore' => 'Placeholder 12 Score',
        'placeholderThirteenScore' => 'Placeholder 13 Score',
        'placeholderFourteenScore' => 'Placeholder 14 Score',
        'placeholderFifteenScore' => 'Placeholder 15 Score',
        'placementSixteenScore' => 'Placeholder 16 Score',
        'placementSeventeenScore' => 'Placeholder 17 Score',
        'placementEighteenScore' => 'Placeholder 18 Score',
        'placementNineteenScore' => 'Placeholder 19 Score',
        'placementTwentyScore' => 'Placeholder 20 Score',
        'leakScore' => 'Losses - Leak Score',
        'complianceScore' => 'Losses - Compliance Score',
        'incidentScore' => 'Losses - Incident Score',
        'hydrocarbonLossesScore' => 'Losses - Hydrocarbon Losses Score',
        'violationScore' => 'Losses - Violation Score',
        'brineLeakScore' => 'Other Losses - Brine Leak Score',
        'h2sLeakScore' => 'Other Losses - H2S Leak Score',
        'priorityScore' => 'Priority Score [0-100]',
    ];
}
