export const scenarioDetailsKeyLabelMap: { [key: string]: string } = {
    wellRank: 'Well Rank',
    // operatorName: 'Operator Name',
    wellId: 'Well ID',
    wellType: 'Well Type [LUOW/DOW]',
    priorityScore: 'Priority Score [0-100]',
    age: 'Age [Years]',
    // annualOilProduction: 'Oil [bbl/Year]',
    // annualGasProduction: 'Gas [Mcf/Year]',
    // fiveYearGasProduction: '5 Year Gas Production [Mcf]',
    // fiveYearOilProduction: '5 Year Oil Production [bbl]',
    // wellName: 'Well Name',
    latitude: 'Latitude',
    longitude: 'Longitude',
    incident: 'Incident',
    violation: 'Violation',
    compliance: 'Compliance',
    leak: 'Leak',
    h2sLeak: 'H2S Leak',
    stateWetlandsCloseRange: 'State Wetlands (0 - 300 ft)',
    stateWetlandsMediumRange: 'State Wetlands (300 - 1,320 ft)',
    federalWetlandsCloseRange: 'Federal Wetlands (0 - 300 ft)',
    federalWetlandsMediumRange: 'Federal Wetlands (300 - 1,320 ft)',
    buildingsCloseRange: 'Buildings (0 - 300 ft)',
    buildingsMediumRange: 'Buildings (300 - 1,320 ft)',
    schoolsWithinDistance: 'Schools Within Distance',
    hospitalsWithinDistance: 'Hospitals Within Distance'
    // lifelongGasProduction: 'Gas Production - Life [Mcf]',
    // lifelongOilProduction: 'Oil Production - Life [bbl]'
};
