<?php

namespace Database\Seeders;

use App\Enum\DatasetImportColumnPriority;
use App\Models\DatasetImportColumn;
use Illuminate\Database\Seeder;

class DatasetImportColumnPhase3Seeder extends Seeder
{
    protected function sanitizeLabel(string $label): string
    {
        // Convert to lowercase
        $label = strtolower($label);

        // Replace spaces and hyphens with underscores
        $label = str_replace([' ', '-'], '_', $label);

        // Remove asterisks
        $label = str_replace('*', '', $label);

        // Remove any text inside square brackets, including the brackets
        $label = preg_replace('/\[[^\]]*\]/', '', $label);

        // Trim any trailing underscores
        $label = rtrim($label, '_');

        return $label;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $columns = collect([
            [
                'label' => 'Well ID',
                'rules' => ['numeric'],
                'order' => 1,
                'validation_messages' => ['Well ID - must be a number'],
                'required' => true,
                'priority' => DatasetImportColumnPriority::REQUIRED,
            ],
            [
                'label' => 'Latitude',
                'order' => 2,
                'rules' => ['numeric'],
                'validation_messages' => ['Latitude or X - must be a number'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::REQUIRED,
            ],
            [
                'label' => 'Longitude',
                'order' => 3,
                'rules' => ['numeric'],
                'validation_messages' => ['Longitude or Y - must be a number'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::REQUIRED,
            ],
            [
                'label' => 'Operator Name',
                'order' => 4,
                'rules' => ['string'],
                'validation_messages' => ['Operator Name - must be a string or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::RECOMMENDED,
            ],
            [
                'label' => 'Well Name',
                'key' => 'well_name',
                'order' => 5,
                'rules' => ['string'],
                'validation_messages' => ['Well Name - must be a string or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::RECOMMENDED,
            ],
            [
                'label' => 'Well Type [Oil, Gas, Combined]',
                'rules' => ['string', 'in:Oil,Gas,Combined'],
                'order' => 6,
                'validation_messages' => ['Well Type - must be a string and Oil, Gas, or Combined'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::RECOMMENDED,
            ],
            [
                'label' => 'Hydrocarbon Losses [Ton/year]',
                'rules' => ['numeric'],
                'order' => 7,
                'validation_messages' => ['Hydrocarbon Losses - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::RECOMMENDED,
            ],
            [
                'label' => 'Age [Years]',
                'rules' => ['numeric'],
                'order' => 8,
                'validation_messages' => ['Age - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::RECOMMENDED,
            ],
            [
                'label' => 'Depth [ft]',
                'rules' => ['numeric'],
                'order' => 9,
                'validation_messages' => ['Depth - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::RECOMMENDED,
            ],
            // Make these for Annual Oil Production andAnnual Gas Production
            [
                'label' => 'Annual Oil Production [bbl/Year]',
                'rules' => ['numeric'],
                'order' => 10,
                'validation_messages' => ['Annual Oil Production - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
                'key' => 'ann_oil_production',
            ],
            [
                'label' => 'Annual Gas Production [Mcf/Year]',
                'rules' => ['numeric'],
                'order' => 11,
                'validation_messages' => ['Annual Gas Production - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
                'key' => 'ann_gas_production',
            ],
            [
                'label' => '5-Year Oil Production [bbl]',
                'rules' => ['numeric'],
                'order' => 12,
                'validation_messages' => ['5-Year Oil Production - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => '5-Year Gas Production [Mcf]',
                'rules' => ['numeric'],
                'order' => 13,
                'validation_messages' => ['5-Year Gas Production - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Lifelong Oil Production [bbl]',
                'rules' => ['numeric'],
                'order' => 14,
                'validation_messages' => ['Lifelong Oil Production - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Lifelong Gas Production [Mcf]',
                'rules' => ['numeric'],
                'order' => 15,
                'validation_messages' => ['Lifelong Gas Production - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Leak [Yes/No]',
                'rules' => ['boolean'],
                'order' => 16,
                'validation_messages' => ['Leak - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Violation [Yes/No]',
                'rules' => ['boolean'],
                'order' => 17,
                'validation_messages' => ['Violation - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Incident [Yes/No]',
                'rules' => ['boolean'],
                'order' => 18,
                'validation_messages' => ['Incident - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Compliance [Yes/No]',
                'rules' => ['boolean'],
                'order' => 19,
                'validation_messages' => ['Compliance - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'H2s Leak [Yes/No]',
                'rules' => ['boolean'],
                'order' => 20,
                'validation_messages' => ['H2s Leak - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'State Wetlands (Near) [Yes/No]',
                'key' => 'state_wetlands_close_range',
                'rules' => ['boolean'],
                'order' => 21,
                'validation_messages' => ['State Wetlands (Near) - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'State Wetlands (Far) [Yes/No]',
                'key' => 'state_wetlands_wide_range',
                'rules' => ['boolean'],
                'order' => 22,
                'validation_messages' => ['State Wetlands (Far) - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Federal Wetlands (Near) [Yes/No]',
                'key' => 'federal_wetlands_close_range',
                'rules' => ['boolean'],
                'order' => 23,
                'validation_messages' => ['Federal Wetlands (Near) - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Federal Wetlands (Far) [Yes/No]',
                'key' => 'federal_wetlands_wide_range',
                'rules' => ['boolean'],
                'order' => 24,
                'validation_messages' => ['Federal Wetlands (Far) - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Buildings (Near) [Yes/No]',
                'key' => 'buildings_close_range',
                'rules' => ['boolean'],
                'order' => 25,
                'validation_messages' => ['Buildings (Near) - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Buildings (Far) [Yes/No]',
                'key' => 'buildings_wide_range',
                'rules' => ['boolean'],
                'order' => 26,
                'validation_messages' => ['Buildings (Far) - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Number of Schools Near the Well (or if there are any 1=Yes 0=No)',
                'key' => 'num_of_schools_near_well',
                'rules' => ['numeric'],
                'order' => 27,
                'validation_messages' => ['Number of Schools Near the Well - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Number of Hospitals Near the Well (or if there are any 1=Yes 0=No)',
                'key' => 'num_of_hospitals_near_well',
                'rules' => ['numeric'],
                'order' => 28,
                'validation_messages' => ['Number of Hospitals Near the Well - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Elevation Delta (Well-to-Road Access Point) [m]',
                'key' => 'elevation_delta',
                'rules' => ['numeric'],
                'order' => 29,
                'validation_messages' => ['Elevation Delta - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Distance to Road [miles]',
                'rules' => ['numeric'],
                'order' => 30,
                'validation_messages' => ['Distance to Road - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Water Source Nearby [Yes/No]',
                'rules' => ['boolean'],
                'order' => 31,
                'validation_messages' => ['Water Source Nearby - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Known Soil or Water Impact [Yes/No]',
                'rules' => ['boolean'],
                'order' => 32,
                'validation_messages' => ['Known Soil or Water Impact - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Population Density [#/km2]',
                'rules' => ['numeric'],
                'order' => 33,
                'validation_messages' => ['Population Density - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'In Tribal Land [Yes/No]',
                'rules' => ['boolean'],
                'order' => 34,
                'validation_messages' => ['In Tribal Land - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Agriculture Area Nearby [Yes/No]',
                'rules' => ['boolean'],
                'order' => 35,
                'validation_messages' => ['Agriculture Area Nearby - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Number of MCWs Nearby [#]',
                'rules' => ['numeric'],
                'order' => 36,
                'validation_messages' => ['Number of MCWs Nearby - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Likely to be Orphaned [Yes/No]',
                'rules' => ['boolean'],
                'order' => 37,
                'validation_messages' => ['Likely to be Orphaned - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Mechanical Integrity Test [#]',
                'rules' => ['numeric'],
                'order' => 38,
                'validation_messages' => ['Mechanical Integrity Test - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Post-Plugging Land Use [Yes/No]',
                'rules' => ['boolean'],
                'order' => 39,
                'validation_messages' => ['Post-Plugging Land Use - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Surface Equipment On Site [Yes/No]',
                'rules' => ['boolean'],
                'order' => 40,
                'validation_messages' => ['Surface Equipment On Site - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Idle Status Duration [Years]',
                'rules' => ['numeric'],
                'order' => 41,
                'validation_messages' => ['Idle Status Duration - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Endangered Species on Site [Yes/No]',
                'rules' => ['boolean'],
                'order' => 42,
                'validation_messages' => ['Endangered Species on Site - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'High Pressure Observed [Yes/No]',
                'rules' => ['boolean'],
                'order' => 43,
                'validation_messages' => ['High Pressure Observed - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Cost of Plugging [USD]',
                'rules' => ['numeric'],
                'order' => 44,
                'validation_messages' => ['Cost of Plugging - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Home Use Gas Well [Yes/No]',
                'rules' => ['boolean'],
                'order' => 45,
                'validation_messages' => ['Home Use Gas Well - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Otherwise Incentivized Well [Yes/No]',
                'rules' => ['boolean'],
                'order' => 46,
                'validation_messages' => ['Otherwise Incentivized Well - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Historical Preservation Site [Yes/No]',
                'rules' => ['boolean'],
                'order' => 47,
                'validation_messages' => ['Historical Preservation Site - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Well Integrity Issues [Yes/No]',
                'rules' => ['boolean'],
                'order' => 48,
                'validation_messages' => ['Well Integrity Issues - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Brine Leak [Yes/No]',
                'rules' => ['boolean'],
                'order' => 49,
                'validation_messages' => ['Well Integrity Issues - must be Yes or No'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'State Code',
                'rules' => ['numeric'],
                'order' => 50,
                'validation_messages' => ['State Code - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'County Code',
                'rules' => ['numeric'],
                'order' => 51,
                'validation_messages' => ['County Code - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Census Tract ID',
                'rules' => ['numeric'],
                'order' => 52,
                'validation_messages' => ['Census Tract ID - must be a number or empty'],
                'required' => false,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
            ],
            [
                'label' => 'Priority Score User Input',
                'key' => 'priority_score_user_input',
                'order' => 53,
                'priority' => DatasetImportColumnPriority::OPTIONAL,
                'required' => false,
                'rules' => [],
                'validation_messages' => [],
            ],
            [
                'label' => 'Placeholder 1',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 2',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 3',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 4',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 5',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 6',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 7',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 8',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 9',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 10',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 11',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 12',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 13',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 14',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 15',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 16',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 17',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 18',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 19',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
            [
                'label' => 'Placeholder 20',
                'rules' => [],
                'validation_messages' => [],
                'required' => false,
            ],
        ]);

        $columns->each(function ($column) {
            DatasetImportColumn::updateOrCreate(
                ['label' => $column['label']],
                [...$column, 'key' => $column['key'] ?? $this->sanitizeLabel($column['label'])]
            );
        });
    }
}
